#!/usr/bin/env python3
"""从原始 PNG 生成 LVGL 内嵌图片资源，或转换旧 RGB565A8 C 资源。

背景
----
原始资源以 ``lv_image_dsc_t`` (RGB565A8, 135x185) 的形式把未压缩像素直接编入
固件 .rodata，55 帧合计约 4MB，导致 T5AI FLASH 溢出。本脚本把每帧的像素还原为
RGBA，再用 PNG 无损压缩（帧中大量透明区域可被极大压缩），并把 .c 改写为
"PNG 字节数组 + cf=LV_COLOR_FORMAT_RAW 的描述符"。运行时由 LVGL 的 lodepng
解码器（需开启 CONFIG_ENABLE_LVGL_LODEPNG）识别 PNG magic 并解码，avatar 帧序列
的引用方式（extern lv_image_dsc_t）保持不变。

RGB565A8 内存布局（LVGL 9，平面式）：
  [ RGB565 平面: w*h*2 字节, 小端 ] 紧接 [ A8 平面: w*h 字节 ]

用法
----
  python convert_assets_to_png.py --source-dir <素材目录> --output-dir <assets目录>
  python convert_assets_to_png.py --check <file.c>   # 仅解析并报告 PNG 体积，不改文件
  python convert_assets_to_png.py --dir <assets_dir>  # 批量原地改写目录下所有 .c
  python convert_assets_to_png.py <file.c> [file.c...] # 原地改写指定文件

注意：本脚本只接受 RGB565A8 原始格式输入，对已转换为 PNG 的文件会报
"数据长度不符" 并跳过改写（不会二次转换损坏数据）。
"""

import argparse
import importlib
import io
import os
import re
import sys
from pathlib import Path

MAP_RE = re.compile(r"(\w+)_map\s*\[\s*\]\s*=\s*\{(.*?)\}\s*;", re.DOTALL)
HEX_RE = re.compile(r"0x([0-9a-fA-F]{1,2})")
FIELD_RE = {
    "w": re.compile(r"\.header\.w\s*=\s*(\d+)"),
    "h": re.compile(r"\.header\.h\s*=\s*(\d+)"),
    "cf": re.compile(r"\.header\.cf\s*=\s*(\w+)"),
    "dsc": re.compile(r"const\s+lv_image_dsc_t\s+(\w+)\s*="),
}

SOURCE_GROUPS = {
    "01_Thinking_reference": ("thinking", "frame_*.png"),
    "02_Coding_reference": ("coding", "frame_*.png"),
    "03_Error_unified": ("error", "fire_glitch_frame_*.png"),
    "04_Celebration_unified": ("celebration", "frame_*.png"),
    "05_Confused_unified": ("confused", "frame_*.png"),
    "07_Moyu_unified": ("moyu", "frame_*.png"),
    "08_Sleep_unified": ("sleep", "frame_*.png"),
    "09_Cycling": ("cycling", "frame_*.png"),
}


def parse_c_asset(path):
    """返回 (var_name, dsc_name, w, h, raw_bytes)。"""
    text = open(path, "r", encoding="utf-8", errors="replace").read()

    m = MAP_RE.search(text)
    if not m:
        raise ValueError(f"{path}: 未找到 *_map[] 数组")
    var_name = m.group(1)
    body = m.group(2)
    raw = bytes(int(x, 16) for x in HEX_RE.findall(body))

    def field(key, cast=int):
        mm = FIELD_RE[key].search(text)
        if not mm:
            raise ValueError(f"{path}: 未找到 .header.{key}")
        return cast(mm.group(1))

    w = field("w")
    h = field("h")
    dsc_m = FIELD_RE["dsc"].search(text)
    dsc_name = dsc_m.group(1) if dsc_m else var_name
    return var_name, dsc_name, w, h, raw


def rgb565a8_to_rgba(raw, w, h):
    """把 RGB565A8 平面数据转换为 RGBA (bytes, 4*w*h)。"""
    npx = w * h
    color_len = npx * 2
    if len(raw) < color_len + npx:
        raise ValueError(
            f"数据长度 {len(raw)} 与 {w}x{h} RGB565A8 (需 {color_len + npx}) 不符"
        )
    color = raw[:color_len]
    alpha = raw[color_len:color_len + npx]

    out = bytearray(npx * 4)
    for i in range(npx):
        lo = color[i * 2]
        hi = color[i * 2 + 1]
        v = lo | (hi << 8)  # 小端
        r5 = (v >> 11) & 0x1F
        g6 = (v >> 5) & 0x3F
        b5 = v & 0x1F
        # 5/6 bit -> 8 bit（复制高位补齐，保证 0->0, max->255）
        r = (r5 << 3) | (r5 >> 2)
        g = (g6 << 2) | (g6 >> 4)
        b = (b5 << 3) | (b5 >> 2)
        o = i * 4
        out[o] = r
        out[o + 1] = g
        out[o + 2] = b
        out[o + 3] = alpha[i]
    return bytes(out)


def encode_png(rgba, w, h):
    image_module = importlib.import_module("PIL.Image")

    img = image_module.frombytes("RGBA", (w, h), rgba)
    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


def load_png(path):
    """读取原始 RGBA PNG，并从 IHDR 校验格式和尺寸。"""
    png = Path(path).read_bytes()
    signature = b"\x89PNG\r\n\x1a\n"
    if len(png) < 33 or not png.startswith(signature) or png[12:16] != b"IHDR":
        raise ValueError(f"{path}: 不是有效的 PNG 文件")

    w = int.from_bytes(png[16:20], "big")
    h = int.from_bytes(png[20:24], "big")
    bit_depth = png[24]
    color_type = png[25]
    if bit_depth != 8 or color_type != 6:
        raise ValueError(
            f"{path}: PNG 格式为 bit_depth={bit_depth}, color_type={color_type}，"
            "预期 8-bit RGBA (color type 6)"
        )
    return w, h, png


def render_c(var_name, dsc_name, w, h, png, source_name=None):
    lines = []
    a = lines.append
    a("#if defined(LV_LVGL_H_INCLUDE_SIMPLE)")
    a("#include \"lvgl.h\"")
    a("#elif defined(LV_BUILD_TEST)")
    a("#include \"../lvgl.h\"")
    a("#else")
    a("#include \"lvgl/lvgl.h\"")
    a("#endif")
    a("")
    if source_name:
        a(f"/* Generated from {source_name}: embedded PNG decoded by LVGL lodepng. */")
    else:
        a("/* Generated by tools/convert_assets_to_png.py: embedded PNG decoded by LVGL lodepng. */")
    a("")
    a("#ifndef LV_ATTRIBUTE_MEM_ALIGN")
    a("#define LV_ATTRIBUTE_MEM_ALIGN")
    a("#endif")
    a("")
    attr_name = f"LV_ATTRIBUTE_IMG_{dsc_name.upper()}"
    a(f"#ifndef {attr_name}")
    a(f"#define {attr_name}")
    a("#endif")
    a("")
    a("static const")
    a(f"LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST {attr_name}")
    a(f"uint8_t {var_name}_map[] = {{")
    # 每行 16 字节
    for i in range(0, len(png), 16):
        chunk = png[i:i + 16]
        a("    " + "".join(f"0x{b:02x}," for b in chunk))
    a("};")
    a("")
    a(f"const lv_image_dsc_t {dsc_name} = {{")
    a("  .header.magic = LV_IMAGE_HEADER_MAGIC,")
    a("  .header.cf = LV_COLOR_FORMAT_RAW_ALPHA,")
    a("  .header.flags = 0,")
    a(f"  .header.w = {w},")
    a(f"  .header.h = {h},")
    a("  .header.stride = 0,")
    a(f"  .data_size = sizeof({var_name}_map),")
    a(f"  .data = {var_name}_map,")
    a("};")
    a("")
    return "\n".join(lines)


def generate_from_source(source_dir, output_dir):
    """按 OpenWaifu 状态目录映射批量生成 LVGL C 图片资源。"""
    source_root = Path(source_dir)
    output_root = Path(output_dir)
    generated = 0

    if not source_root.is_dir():
        raise ValueError(f"素材目录不存在: {source_root}")
    output_root.mkdir(parents=True, exist_ok=True)

    for folder, (prefix, pattern) in SOURCE_GROUPS.items():
        paths = sorted((source_root / folder).glob(pattern))
        if not paths:
            raise ValueError(f"未找到素材: {source_root / folder / pattern}")

        for index, path in enumerate(paths, start=1):
            w, h, png = load_png(path)
            if (w, h) != (135, 185):
                raise ValueError(f"{path}: 尺寸为 {w}x{h}，预期 135x185")

            name = f"{prefix}_{index:02d}"
            output = output_root / f"{name}.c"
            output.write_text(
                render_c(name, name, w, h, png, f"{folder}/{path.name}"),
                encoding="utf-8",
            )
            generated += 1
            print(f"{name:24s} {len(png):7d} bytes  <- {folder}/{path.name}")

    print("-" * 60)
    print(f"已生成 {generated} 个 LVGL 内嵌 PNG 资源到 {output_root}")


def convert_file(path, write=True):
    var_name, dsc_name, w, h, raw = parse_c_asset(path)
    rgba = rgb565a8_to_rgba(raw, w, h)
    png = encode_png(rgba, w, h)
    if write:
        out = render_c(var_name, dsc_name, w, h, png)
        with open(path, "w", encoding="utf-8") as f:
            f.write(out)
    return len(raw), len(png)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("files", nargs="*", help="要转换的 .c 文件")
    ap.add_argument("--dir", help="批量转换该目录下所有 .c")
    ap.add_argument("--source-dir", help="OpenWaifu 原始 PNG 素材根目录")
    ap.add_argument("--output-dir", help="--source-dir 模式的 C 资源输出目录")
    ap.add_argument("--check", action="store_true",
                    help="仅报告体积，不改写文件")
    args = ap.parse_args()

    if args.source_dir:
        if not args.output_dir:
            ap.error("--source-dir 必须与 --output-dir 一起使用")
        try:
            generate_from_source(args.source_dir, args.output_dir)
        except Exception as e:  # noqa: BLE001
            print(f"[FAIL] {e}", file=sys.stderr)
            return 1
        return 0

    targets = list(args.files)
    if args.dir:
        targets += sorted(
            os.path.join(args.dir, f)
            for f in os.listdir(args.dir)
            if f.endswith(".c")
        )
    if not targets:
        ap.error("未指定文件或目录")

    total_raw = 0
    total_png = 0
    for path in targets:
        try:
            raw_len, png_len = convert_file(path, write=not args.check)
        except Exception as e:  # noqa: BLE001
            print(f"[FAIL] {path}: {e}", file=sys.stderr)
            return 1
        total_raw += raw_len
        total_png += png_len
        ratio = png_len / raw_len * 100 if raw_len else 0
        print(f"{os.path.basename(path):24s} raw={raw_len:7d}  png={png_len:6d}  ({ratio:5.1f}%)")

    print("-" * 60)
    print(f"合计: raw={total_raw} ({total_raw/1024/1024:.2f} MB)  "
          f"png={total_png} ({total_png/1024/1024:.2f} MB)  "
          f"压缩到 {total_png/total_raw*100:.1f}%")
    if not args.check:
        print("已原地改写上述文件。")
    return 0


if __name__ == "__main__":
    sys.exit(main())
